language: android

jdk:
 - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-24
    - build-tools-24.0.1
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &

env:
  global:
    - ADB_INSTALL_TIMEOUT=8